server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:mysql://localhost:3306/student?useSSL=false&useFractionalSeconds=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false