server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:postgresql://localhost:5432/department?useSSL=false&useFractionalSeconds=true
    username: sa
    password: PasswordO1.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false

---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    url: jdbc:postgresql://postgres:5432/department?useSSL=false&useFractionalSeconds=true