server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'
  application:
    name: '@project.artifactId@'
  mysql:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/student?useSSL=false&useFractionalSeconds=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      show-sql: false
      use-sql-comments: false
      ddl-auto: none
      use-query-cache: false
      use-second-level-cache: false
      dialect: org.hibernate.dialect.MySQL57Dialect
  mariadb:
    datasource:
      jdbc-url: jdbc:mariadb://localhost:3307/teacher?useSSL=false&useFractionalSeconds=true
      username: root
      password: PasswordO1.
      driver-class-name: org.mariadb.jdbc.Driver
    hibernate:
      show-sql: false
      use-sql-comments: false
      ddl-auto: none
      use-query-cache: false
      use-second-level-cache: false
      dialect: org.hibernate.dialect.MySQL57Dialect
  postgres:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/department?useSSL=false&useFractionalSeconds=true
      username: sa
      password: PasswordO1.
      driver-class-name: org.postgresql.Driver
    hibernate:
      show-sql: false
      use-sql-comments: false
      ddl-auto: none
      use-query-cache: false
      use-second-level-cache: false
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: beta
  mysql.datasource:
    jdbc-url: jdbc:mysql://mysql_db:3306/student?useSSL=false&useFractionalSeconds=true
  mariadb.datasource:
    jdbc-url: jdbc:mariadb://maria_db:3306/teacher?useSSL=false&useFractionalSeconds=true
  postgres.datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/department?useSSL=false&useFractionalSeconds=true