server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'
  application:
    name: '@project.artifactId@'
  mysql:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/student?useSSL=false&useFractionalSeconds=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      show-sql: true
      use-sql-comments: true
      ddl-auto: none
      use-query-cache: false
      use-second-level-cache: false
      dialect: org.hibernate.dialect.MySQL57Dialect