version: "3.6"

services:

  mysql_db:
    image: bitnami/mysql:8.0
    container_name: mysql_db
    hostname: mysql_db
    ports:
      - '3306:3306'
    volumes:
      - 'multi_database_mysql_data:/bitnami/mysql/data'
      - './db.scripts/mysql/:/docker-entrypoint-initdb.d/'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network_multi_database
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  maria_db:
    image: mariadb:10.6.4
    container_name: maria_db
    hostname: maria_db
    ports:
      - '3307:3306'
    volumes:
      - 'multi_database_mariadb_data:/var/lib/mysql'
      - './db.scripts/mariadb/:/docker-entrypoint-initdb.d/'  #para esta version se debe crear una BBDD (MARIADB_DATABASE), solo si hay una BBDD creada se ejecuta el script
    environment:
      - MARIADB_ROOT_PASSWORD=PasswordO1.
      - MARIADB_PASSWORD=PasswordO1.
      - MARIADB_USER=sa
      - MARIADB_DATABASE=teacher
    networks:
      - network_multi_database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  postgres:
    image: postgres:13.4
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: PasswordO1.
      POSTGRES_USER: sa
      POSTGRES_DB_CUSTOM: department
    volumes:
      - 'multi_database_postgres_data:/var/lib/postgresql/data'
      - './db.scripts/postgres/:/docker-entrypoint-initdb.d/'
    networks:
      - network_multi_database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  java_multi_database_app:
    image: java_multi_database_app
    container_name: java_multi_database_app
    hostname: java_multi_database_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9292:9292"
    depends_on:
      - mysql_db
      - maria_db
      - postgres
    networks:
      - network_multi_database

networks:
  network_multi_database:
    name: network_multi_database

volumes:
  multi_database_mariadb_data:
    driver: local
  multi_database_mysql_data:
    driver: local
  multi_database_postgres_data:
    driver: local