version: "3.6"

services:
  mysql_db:
    image: bitnami/mysql:8.0
    container_name: mysql_db
    hostname: mysql_db
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
      - './db.scripts/:/docker-entrypoint-initdb.d/'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network_sql
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  java_mysql_app:
    image: java_mysql_app
    container_name: java_mysql_app
    hostname: java_mysql_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9292:9292"
    depends_on:
      - mysql_db
    #links:
    #  - mysql:mysql
    networks:
      - network_sql


networks:
  network_sql:
    name: network_sql

volumes:
  mysql_data:
    driver: local