version: "3.6"

services:
  maria_db:
    image: mariadb:10.6.4
    container_name: maria_db
    hostname: maria_db
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
      - './db.scripts/mariadb/:/docker-entrypoint-initdb.d/'  #para esta version se debe crear una BBDD (MARIADB_DATABASE), solo si hay una BBDD creada se ejecuta el script
    environment:
      - MARIADB_ROOT_PASSWORD=PasswordO1.
      - MARIADB_PASSWORD=PasswordO1.
      - MARIADB_USER=sa
      - MARIADB_DATABASE=teacher
    networks:
      - network_mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  java_miriadb_app:
    image: java_miriadb_app
    container_name: java_miriadb_app
    hostname: java_miriadb_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9292:9292"
    depends_on:
      - maria_db
    networks:
      - network_mariadb


networks:
  network_mariadb:
    name: network_mariadb

volumes:
  mariadb_data:
    driver: local